config/routes.rb
Rails.application.routes.draw do
 
  get 'notifications/index'

  get 'notifications/create'

  get 'comments/comments'

  #get 'welcome/index'
  #match ':controller(/:action(/:id))', :via => :get


  #root 'welcome#login'
  devise_for :users


  resources :messages, except: :create do
  	post 'create_user' => 'admins_controller#create', as: :create_user  
  	resources :comments
  end
  resources :upload_files
  root 'messages#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base

	has_one :image
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}, :path => ":rails_root/public/my_addr/:user_id/:style/:basename.:extension",
  :url => "/my_addr/:user_id/:style/:basename.:extension"

	belongs_to :user
	has_many :comments
	validates_presence_of :title



	
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image_file_name, :image_content_type, :image_file_size
  belongs_to :accommodation
  has_attached_file :image,
    :styles => {
      :thumb=> "100x100#",
      :small  => "150x150>" }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
end

app/controllers/admins_controller_controller.rb
class AdminsControllerController < ApplicationController
	def create
        build_resource(sign_up_params)
        if resource.save
          redirect_to admin_editors_path
        else
          clean_up_passwords resource
          respond_with resource
        end
      end

      def new
        build_resource({})
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
	@message = Message.find(params[:message_id])
	@comment = @message.comments.create(params.require(:comment).permit(:content))
	@comment.user_id = current_user.id

	if @comment.save
		redirect_to message_path(@message)
	else
		render 'new'
	end 
end	

	def edit 
		@message = Message.find(params[:message_id])
		@comment = @message.comments.find(params[:id])
	end

	def update
		@message = Message.find(params[:message_id])
		@comment = @message.comments.find(params[:id])
		if @comment.update(params.require(:comment).permit(:content))
			redirect_to message_path(@message)
		else
			render 'edit'
	end
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	before_action :authenticate_user!
	
	
	def index
		@messages = Message.all.order("created_at DESC")
	end

	def show

		@message = Message.find(params[:id])
	end

	def new
		@message = current_user.messages.build
		
	end

	def create


		@message = current_user.messages.build(message_params)
		if @message.save
	
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		
		@message = Message.find params[:id]
	end

	def update

		@message = Message.find params[:id]
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message = Message.find params[:id]
		@message.destroy
		redirect_to root_path
	end


	private 
	def message_params
		params.require(:message).permit(:title, :description, :job, :status, :customer,image: [:file_name, :image_file_size, :image_content_type, :image_updated_at])
	end

	def service_params
		 params.require(:service).permit(:photo)
		end


end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  end

  
end

app/helpers/admins_controller_helper.rb
module AdminsControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div>
<p><%= comment.content %>
<p>Posted by <%= comment.user.try(:email) %> <%= time_ago_in_words(comment.created_at) %> ago</p>
<% if user_signed_in?  %>
<% if comment.user.id == current_user.id %>
<%= link_to "Update", edit_message_comment_path(comment.message, comment) %></p>
</div>
<% end %>
<hr>
<% end %>










	<style media="screen" type="text/css">

p {
width: 900px;
margin: auto;
border-radius: 10px;
}

p a{
	text-decoration: none;
	color: black;
	font-weight: bold;
}

div {
	padding-top: 20px;
}

hr {
width: 60%;
color:#D8D8D8;
}
	</style>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: false, input_html: {style: 'height:200px;' 'width: 700px'} %>
	<center><%= f.button :submit %></center>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment </h1>
<%= simple_form_for([@message, @comment]) do |f| %>
<%= f.input :content, label: "Comment" %>
<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ERF - Schaffner</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="communication.js"></script>
  <%= csrf_meta_tags %>
</head>
<body> 

<ul>
	<li><%= link_to "Home", root_path, class:"list" %></li>
	<li><%= link_to "New ERF", new_message_path, class:"list" %></li>
	<li><%= link_to "Register User", new_user_registration_path, class:"list"%></li>
	<% if user_signed_in? %>
		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"list"%></li>
	<% else%>
		<li><%= link_to "Log In", new_user_session_path, class:"list" %><li>
	<% end %>
</ul>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>


<style media="screen" type="text/css">

.list {
    color: white;
    font-size: 18px;
    font-family: "Arial";
    text-decoration: none;

}

li {
	display:inline;
	padding-right: 150px;
    margin: auto;
}


ul {
    list-style-type: none;
    margin: 0;
    overflow: hidden;
    background-color: #333;
    height: 30px;
    text-align: center;
    padding left:60px;
    padding-top: 10px;
    position: relative;
    display: flex;
    justify-content: space-between;
}


</style>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message, url: messages_path, html: { multipart: true }  do |f| %>

	<div id = 'list'>
	<div class ="color"><%= f.select :status, [['Completed','completed'],['In Progress','in progress'],['Rejected','rejected']], label: "Status",input_html: {style: 'height:20px;' 'width: 274px'}%></div>
	<br>
	<br>
	<%= f.input :customer, label: "Customer", input_html: {style: 'height:20px;' 'width: 274px'}%>
	<%= f.input :job, label: "Job Number", input_html: {style: 'height:20px;' 'width: 274px'}%>
	<%= f.input :title, label: "Title", input_html: {style: 'height:20px;' 'width: 274px'}%>
	<%= f.file_field :image, class: "form-control" %> 

	</div>

	<br>
	<%= f.input :description, input_html: {style: 'height:300px;' 'width: 700px'} %>
	<br>
	<div class = 'button'><%= f.button :submit, label: "Submit" %></div>
	<br>
	<br>

	<br>
<% end %>

<style media="screen" type="text/css">

.list {
	position: relative;
	text-align: left;
}


.button {
	
	text-align: center;
	left: 46%;
}

</style>

app/views/messages/edit.html.erb
<center><h1>Edit Message</h1></center>

<center><%= render 'form' %></center>

app/views/messages/index.html.erb
<h1>Engineering Change Requests</h1>

<table id = "requests" class="display" cellspacing="0" width="%">
	<thead>
	<tr>
		<th>Name of Request</th>
		<th>Job Number</th>
		<th>Date Created</th>
		<th>Customer</th>
		<th>Status</th>
	</tr>
</thead>
<tbody>
	<% @messages.each do |message| %>
	<tr>
	<div class = 'info'>
		<td><%= link_to  message.title , message_path(message)%></td>
		
		<td><%= message.job %></td>
		<td><%= message.created_at.strftime("%b %d, %Y") %></td>
		<td><%= message.customer %></td>
		<td><%= message.status %></td>
	
	</div>
	</tr>
<% end %>
</tbody>
</table>

<script>
$(document).ready(function() {
    $('#requests').DataTable();
} );</script>


<style media="screen" type="text/css">

h1{
	text-align: center;
}

td a{
text-decoration: none;
color: black;
	
}

tbody {
	left: 50%;
}

td {
    text-align: center;
}

</style>

app/views/messages/new.html.erb
<h1>New Engineering Change Request</h1>

<div id="container">
    <div id="first"><%= render 'form' %></div>

    <div id="clear"></div>
</div>

<a href = "/new_notification/create">Send</a> a message via Gmail!
<style media="screen" type="text/css">

h1 {
	margin-top: 100px;
	text-align: center;
	position: relative;

}


#container {
    margin: auto;
    margin-top: 20px;
    text-align: center;
    width: 1000px;
 
}
#first {
    padding-left: 40px
    width: 200px;
    float: left;
    text-align: center;


}
#second {
    width: 300px;
    float: right;
    height: 400px;
    text-align: right;
    border-style: solid;
    border-width: 1px;
  
}

</style>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2>

<center><h5 id = "posted_by">Posted by <%= @message.user.try(:email) %> <%= time_ago_in_words(@message.created_at) %> ago</h5></center>

<div id = 'container'>
	<p>Job Number: <%= @message.job %></p>
	<p>Status: <%= @message.status %></p>
	<p><%=  @message.description %></p>



 
	<div>
<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_message_path(@message) %>
<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?"} %>
</div>
</div>

	<h2>Comments:</h2>
	<div id = 'comment'>
		<%= render @message.comments %>
	</div>

<h2>Reply:</h2>
	<%= render 'comments/form' %>

<div class = "image">
<img style="position: absolute; bottom:0;" src="http://r3.masstransitmag.com/files/base/MASS/image/2016/02/16x9/640x360/Logo_Schaffner_slogan2020.56ce0a5bacddd.jpg" height="100">
</div>

<style media="screen" type="text/css">

h2 {
	position: relative;
	text-align: center;
}

.posted_by {
	color: #E6E6E6;
}

p {
	position: relative;
	text-align: left;
	padding: 20px 20px 20px 20px;
	width: 850px;
}

div {
	text-align: center;
}

#container {
    width: 900px;
    background-color: #F2F2F2;
    margin: auto;
    border-radius: 10px

}
.image {
	margin-left: 50%;
	margin-right: 50%;
	
}



</style>

app/views/notifications/index.html.erb
<a href = "/notifications/create">Send</a>a message via Gmail!

app/views/notifier/notifier.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Hi <%= @user.name %></h1>
    <p>
      Sample mail sent using smtp.
    </p>
  </body>
</html>

app/views/notifier/notifier.text.erb
Hi <%= @user.name %>
Sample mail sent using smtp.

app/views/welcome/extra.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= "Count to 10"%>
<br/>
<% 11.times do |i| %>
<%=i%>
<%end%>

<%= "Message from controller : #{@controller_message}"%>

app/views/welcome/login.html.erb
<h1 align="center">Engineering Request Form Login</h1>

<body>
<center><p>Username:</p></center>
<center><input type="text" name="username">
  <br></center>
<center><p>Password:</p></center>
<center><input type="text" name="password"></center>
	<br>
	<center><button type="button">Log In</button></center>

</body>

<div>
<img style="position: fixed; bottom:0;" src="http://r3.masstransitmag.com/files/base/MASS/image/2016/02/16x9/640x360/Logo_Schaffner_slogan2020.56ce0a5bacddd.jpg" height="200">
</div>

<style media="screen" type="text/css">

body{
padding-top: 100px;
}
div {
	display: block;
	margin-left: 38%;
	margin-right: 50%;
	
}
</style>

app/views/welcome/sample.html.erb
<h1>Welcome#Sample</h1>
<p>Find me in app/views/welcome/sample.html.erb</p>

<center><%= "Message from controller : #{@controller_message}"%></center>

<%= link_to("Go to Index", {:controller => 'welcome', :action => 'index'}) %>

<center><img style="position: fixed; bottom:0;" src="http://photos.prnewswire.com/prn/20110901/LA61098LOGO" align="center"></center>